'use strict';
const { test, before, after, beforeEach, afterEach } = require('node:test');
const assert = require('node:assert/strict');
const Tester = require('./lib/options');
async function expectFailure(fn) {
 await assert.rejects(async () => {
  await Promise.resolve().then(() => fn());
 });
}
if (Tester.before) before(Tester.before);
if (Tester.after) after(Tester.after);
if (Tester.beforeEach) beforeEach(Tester.beforeEach);
if (Tester.afterEach) afterEach(Tester.afterEach);
test('Options: Missing Configuration (Error)', async () => { await expectFailure(Tester.valConfMissing); });
test('Options: Null Universe (Error)', async () => { await expectFailure(Tester.valUnivNull); });
test('Options: Null Universe DB (Error)', async () => { await expectFailure(Tester.valUnivDbNull); });
test('Options: Empty Universe DB (Error)', async () => { await expectFailure(Tester.valUnivDbEmpty); });
test('Options: Null Host (Error)', async () => { await expectFailure(Tester.valHostNull); });
test('Options: Null DB (Error)', async () => { await expectFailure(Tester.valDbNull); });
test('Options: Null Dialects (Error)', async () => { await expectFailure(Tester.valDialectsNull); });
test('Options: Empty Dialects (Error)', async () => { await expectFailure(Tester.valDialectsEmpty); });
test('Options: Custom Loggers', async () => { await Tester.valLoggers(); });
test('Options: Null Connections (Error)', async () => { await expectFailure(Tester.valConnectionsNull); });
test('Options: Empty Connections (Error)', async () => { await expectFailure(Tester.valConnectionsEmpty); });
test('Options: Missing ID Connections (Error)', async () => { await expectFailure(Tester.valConnectionsIdMissing); });
test('Options: Missing Name Connections (Error)', async () => { await expectFailure(Tester.valConnectionsNameMissing); });
test('Options: Missing Dir Connections', async () => { await Tester.valConnectionsDirMissing(); });
test('Options: Missing Dialect Connections (Error)', async () => { await expectFailure(Tester.valConnectionsDialectMissing); });
test('Options: Invalid Dialect Connections (Error)', async () => { await expectFailure(Tester.valConnectionsDialectinvalid); });
test('Options: Mismatch Dialect Connections (Error)', async () => { await expectFailure(Tester.valConnectionsDialectMismatch); });
test('Options: External Dialect Connections (Error)', async () => { await expectFailure(Tester.valConnectionsDialectImportExternal); });
test('Options: Duplicate Connections (Error)', async () => { await expectFailure(Tester.valConnectionsIdDuplicate); });
test('Options: Connections Substitutes', async () => { await Tester.valConnectionsSubstitutes(); });
test('Options: Connections Binds', async () => { await Tester.valConnectionsBinds(); });
test('Options: Missing Connections Driver Options', async () => { await Tester.valConnectionsDriverOptionsMissing(); });
test('Options: Connections Log None', async () => { await Tester.valConnectionsLogNone(); });
test('Options: Connections Log Custom Tags', async () => { await Tester.valConnectionsLogTags(); });
test('Options: Connections Log Custom Tags (with custom logger)', async () => { await Tester.valConnectionsLogTagsWithCustomLogger(); });
test('Options: Nonexistent Main Path (Error)', async () => { await expectFailure(Tester.valNonexistentMainPath); });
test('Options: Empty DB In Main Path', async () => { await Tester.valMainPathEmpty(); });
test('Options: Custom Private Path', async () => { await Tester.valPrivatePath(); });
test('Options: Init Error Return', async () => { await Tester.valInitErrorReturn(); });
test('Options: Reinitialize Manager (Error)', async () => { await expectFailure(Tester.valReinit); });
test('Options: Debug', async () => { await Tester.valDebug(); });