SELECT TDB.SOME_COL1,
TDB.SOME_COL2, TDB.SOME_COL3
FROM TEST_DB
INNER JOIN SOME_OTHER_DB.TEST2_DB TEST2_DB ON TEST2_DB.SOME_COL1 = TEST_DB.SOME_COL1
WHERE TDB.SOME_COL1 = :someCol1
AND TDB.SOME_COL2 = :someCol2
AND TDB.SOME_COL3 = :someCol3